continue clonedeploy move

diff --git a/Toems-ClientApi/private/clientscripts/lie_global_functions b/Toems-ClientApi/private/clientscripts/lie_global_functions
--- a/Toems-ClientApi/private/clientscripts/lie_global_functions
+++ b/Toems-ClientApi/private/clientscripts/lie_global_functions
@@ -348,96 +348,6 @@ function log_boot_args()
 	log "Boot Image Version: $(cat /etc/cd_version)"
 }
 
-
-function mount_smb()
-{
-	local mount_result
-	local all_cluster_dps
-	local result
-	
-	log " ** Mounting SMB Share **" "display"
-	mkdir /storage &>> $CLIENT_LOG
-	smbInfo=$($curlAuth --data "dpId=$dp_id&task=$task" "${web}DistributionPoint" $curlEnd)
-	log " ...... Connecting To $(parse_json "$smbInfo" .DisplayName)" "display"
-	if [ "smb_debug" = "1" ]; then
-	  log "$smbInfo"
-	fi
-	
-	mount_result=$(mount_smb_sub "$smbInfo")
-	if [ "$mount_result" = "true" ]; then
-	  log " ...... Success" "display"
-	else
-	  #Look for other distribution points
-	  log " ...... Looking For Additional Distribution Points"
-	  all_cluster_dps=$($curlAuth --data "computerId=$computer_id" "${web}GetAllClusterDps" $curlEnd)
-	  if [ ! "$?" = "0" ]; then
-		error "Could Not Find Additional Distribution Points"
-	  else
-	    if [ "$all_cluster_dps" = "single" ]; then
-			error "Could Not Mount SMB Share and Server Is Not Clustered"
-		elif [ "$all_cluster_dps" = "false" ]; then
-			error "Could Not Mount SMB Share and An Unknown Error Occurred While Looking For Others"
-		else
-			for local_dp_id in $all_cluster_dps; do
-			  sleep 2
-			  smbInfo=$($curlAuth --data "dpId=$local_dp_id&task=$task" "${web}DistributionPoint" $curlEnd)
-			  log " ...... Connecting To $(parse_json "$smbInfo" .DisplayName)" "display"
-			  if [ "smb_debug" = "1" ]; then
-				log "$smbInfo"
-			  fi
-			  mount_result=$(mount_smb_sub "$smbInfo")
-			  if [ "$mount_result" = "true" ]; then
-			    log " ...... Success" "display"
-				dp_id=$local_dp_id
-				result="true"
-				break
-			  else
-			    result="false"
-			  fi
-			done
-			
-			if [ "$result" = "false" ]; then
-			  #no smb shares could be mounted
-			  error "Could Not Mount Any Available SMB Shares"
-			fi
-		fi
-	  fi
-	fi
-	
-	echo
-	sleep 2
-}
-
-function mount_smb_sub()
-{
-	local smbInfo=$1
-	
-	for smbVersion in 3.0 2.1 2.0 1.0; do	
-		mount -t cifs "$(parse_json "$smbInfo" .SharePath)" /storage -o user="$(parse_json "$smbInfo" .Username)",pass="$(parse_json "$smbInfo" .Password)",dom="$(parse_json "$smbInfo" .Domain)",vers=$smbVersion 2>/tmp/mntstat
-		if [ ! $? = "0" ]; then
-			cat /tmp/mntstat >> $CLIENT_LOG
-			errormsg=$(cat /tmp/mntstat)
-		else
-			cd /storage/images/$image_name;
-			if [ "$?" != "0" ]; then
-				log " ...... Could Not Change Directory To /storage/images/$image_name Check Permissions" "display"
-				cd /
-			    umount /storage
-			    echo "false"
-			else
-				echo "true"
-			fi
-			
-			break
-		fi
-		
-		if [ "$smbVersion" = "1.0" ]; then
-			log " ...... Could Not Mount SMB Share" "display"
-			echo "false"
-		fi
-	done
-}
-
 function move_to_front_of_list()
 {
   local item=$1
@@ -589,5 +499,35 @@ $value
 q
 y
 EOFN
+}
+
+function verify_image_server()
+{
+  log " ** Verifying Image Server ** " "display"
+  #Check returned an image_server verify connection
+  imageServerStatus=$($curlAuth "${image_server}Test" $curlEnd)
+  if [ "$imageServerStatus" = "true" ]; then
+    export web="$image_server" #update web to use the image server, may be the same as web already was
+	 log " ...... Success" "display"
+	 echo
+  else
+     log " ...... Failed. Looking For Additional Image Servers"
+	 all_image_servers=$($curlAuth --data "computerId=$computer_id" "${web}GetOtherImageServers" $curlEnd)
+	 if [ ! "$?" = "0" ] || [ "$all_image_servers" = "false" ]; then
+	   error "Could Not Find Any Usable Image Servers"
+	 fi
+	 
+	 for image_server_url in $all_image_servers; do
+	   log " ..... Connecting To ${image_server_url}" "display"
+       sleep 2
+	   imageServerStatus=$($curlAuth "${image_server_url}Test" $curlEnd)
+	   if [ "$imageServerStatus" = "true" ]; then
+         export web="$image_server_url" #update web to use the image server
+	     log " ...... Success" "display"
+		 return 0
+	   fi
+	 done
+	  error "Could Not Find Any Usable Image Servers"
+  fi
 }
 
